all:
  hosts:
    localhost:
      ansible_connection: local
      ssh_hosts:
        - 192.168.122.108
        - 192.168.122.114
        - 192.168.122.128
        - aaron.local
        - peaurouge.local
        - cyclope.local
  children:
    TP:
      hosts:
        aaron:
          ansible_host: 192.168.122.108
        peaurouge:
          ansible_host: 192.168.122.114
        cyclope:
          ansible_host: 192.168.122.128
      vars:
        ansible_user: tpuser
        ansible_password: 7^ytf=6KtZ<8'fE$
        ansible_sudo_pass: 7^ytf=6KtZ<8'fE$
        redis_password: tpuser
        sftp_user: sftp
        sftp_password: tpuser
    VPN:
      hosts:
        cyclope:
          ansible_host: 192.168.122.128
        peaurouge:
          ansible_host: 192.168.122.114
      vars:
        ansible_user: tpuser
        ansible_password: 7^ytf=6KtZ<8'fE$
        ansible_sudo_pass: 7^ytf=6KtZ<8'fE$
    CutNetwork:
      hosts:
        cyclope:
          ansible_host: 192.168.122.128
        aaron:
          ansible_host: 192.168.122.108
      vars:
        ansible_user: tpuser
        ansible_password: 7^ytf=6KtZ<8'fE$
        ansible_sudo_pass: 7^ytf=6KtZ<8'fE$
