basePath: /api
info:
  contact: {}
  license:
    name: Apache 2.0
  title: uploadFile
  version: "1.0"
paths:
  /file/upload:
    post:
      consumes:
      - multipart/form-data
      description: Upload file
      parameters:
      - description: this is a test file
        in: formData
        name: myFile
        required: true
        type: file
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Upload file
swagger: "2.0"
