- hosts: "VPN"
  name: "Install OpenVPN sur les VM"
  become: true
  tasks:
    - name: apt
      apt:
        update_cache: yes
        name: "openvpn"
- hosts: localhost
  name: "Generate OpenVpn certificate"
  tasks:
    - name: "Generate OpenVpn certificate"
      shell: "sudo openvpn --genkey --secret /etc/openvpn/ta.key"
- hosts: localhost
  name: Change ownership of /etc/openvpn/ta.key
  become: true
  tasks:
    - name: "Change ownership of /etc/openvpn/ta.key"
      file:
        path: /etc/openvpn/ta.key
        owner: tpuser
        group: tpuser
        mode: 0600
- hosts: "VPN"
  name: "Copy certificate to PeauRouge and Cyclope"
  become: true
  tasks:
    - ansible.builtin.copy:
        src: /etc/openvpn/ta.key
        dest: /etc/openvpn/ta.key
        owner: tpuser
        group: tpuser
        mode: 0640
        remote_src: false
- hosts: "cyclope"
  name: "Copy configuration server to Cyclope"
  become: true
  tasks:
    - ansible.builtin.copy:
        src: Vpn/Server.conf
        dest: /etc/openvpn/server.conf
        owner: tpuser
        group: tpuser
        mode: 0640
        remote_src: false
    - name: Start Service
      command: "sudo systemctl enable openvpn@server.service"
- hosts: "peaurouge"
  name: "Copy configuration server to PeauRouge"
  become: true
  tasks:
    - ansible.builtin.copy:
        src: Vpn/Client.conf
        dest: /etc/openvpn/client.conf
        owner: tpuser
        group: tpuser
        mode: 0640
        remote_src: false
    - name: Start Service OpenVPN
      command: "sudo systemctl enable openvpn@client.service"
- hosts: "cyclope"
  name: "Ping PeauRouge"
  tasks:
    - name: Ping PeauRouge
      ping:
        host: 10.8.3.2
        count: 4
- hosts: "PeauRouge"
  name: "Ping cyclope"
  tasks:
    - name: Ping cyclope
      ping:
        host: 10.8.3.1
        count: 4
