- hosts: "aaron"
  become: true
  tasks:
    - name: Rename
      command: "sudo hostname aaron"
      ignore_errors: true
    - name: addP1
      command: "sudo ip a add 10.8.0.2/24 dev enp9s0"
      ignore_errors: true
    - name: enableP1
      command: "sudo ip link set enp9s0 up"
      ignore_errors: true
    - name: addP2
      command: "sudo ip a add 10.8.1.2/24 dev enp10s0"
      ignore_errors: true
    - name: enableP2
      command: "sudo ip link set enp10s0 up"
      ignore_errors: true
- hosts: "peaurouge"
  become: true
  tasks:
    - name: Rename
      command: "sudo hostname peaurouge"
      ignore_errors: true
    - name: addP1
      command: "sudo ip a add 10.8.0.1/24 dev enp9s0"
      ignore_errors: true
    - name: enableP1
      command: "sudo ip link set enp9s0 up"
      ignore_errors: true
    - name: LinkPeauRougeCyclope
      command: "sudo ip route add 10.8.1.1 via 10.8.0.2 dev enp9s0"
      ignore_errors: true
- hosts: "cyclope"
  become: true
  tasks:
    - name: Rename
      command: "sudo hostname cyclope"
      ignore_errors: true
    - name: addP2
      command: "sudo ip a add 10.8.1.1/24 dev enp10s0"
      ignore_errors: true
    - name: enableP1
      command: "sudo ip link set enp10s0 up"
      ignore_errors: true
    - name: LinkPeauRougeCyclope
      command: "sudo ip route add 10.8.0.1 via 10.8.1.2 dev enp10s0"
      ignore_errors: true
- hosts: "aaron"
  become: true
  tasks:
    - name: "Edit Line if exist"
      ignore_errors: true
      lineinfile:
        path: /etc/sysctl.conf
        regexp: "#net.ipv4.ip_forward=1"
        line: net.ipv4.ip_forward=1
        state: present
        backup: yes
    - name: "Insert if line not exist"
      ignore_errors: true
      lineinfile:
        path: /etc/sysctl.conf
        line: net.ipv4.ip_forward=1
        state: present
        backup: yes
    - name: "Enable ipv4 forwarding"
      command: "sudo sysctl -p /etc/sysctl.conf"
      ignore_errors: true
