- hosts: "VPN"
  name: "Install OpenVPN sur les VM"
  become: true
  tasks:
    - name: apt
      apt:
        update_cache: yes
        name: "openvpn"
- hosts: localhost
  name: "Generate OpenVpn certificate"
  tasks:
    - name: "Generate OpenVpn certificate"
      shell: "sudo openvpn --genkey --secret /etc/openvpn/ta.key"
- hosts: "VPN"
  name: "Copy certificate to PeauRouge and Cyclope"
  become: true
  tasks:
    - ansible.builtin.copy:
        src: /etc/openvpn/ta.key
        dest: /etc/openvpn/ta.key
        owner: tpuser
        group: tpuser
        mode: 0640
        remote_src: false
- hosts: "cyclope"
  name: "Copy configuration server to Cyclope"
  become: true
  tasks:
    - ansible.builtin.copy:
        src: ../Vpn/Server.conf
        dest: /etc/openvpn/server.conf
        owner: tpuser
        group: tpuser
        mode: 0640
        remote_src: false
    - name: Enable Service OpenVPN
      command: "sudo systemctl enable openvpn@server.service"
    - name: Start Service OpenVPN
      command: "sudo systemctl start openvpn@server.service"
- hosts: "peaurouge"
  name: "Copy configuration Client to PeauRouge"
  become: true
  tasks:
    - ansible.builtin.copy:
        src: ../Vpn/Client.conf
        dest: /etc/openvpn/client.conf
        owner: tpuser
        group: tpuser
        mode: 0640
        remote_src: false
    - name: Enable Service OpenVPN
      command: "sudo systemctl enable openvpn@client.service"
    - name: Start Service OpenVPN
      command: "sudo systemctl start openvpn@client.service"
    - name: Restart Service OpenVPN
      command: "sudo systemctl restart openvpn@client.service"
