- hosts: "peaurouge"
  become: true
  name: "Copy backend"
  tasks:
    - name: "Copy backend"
      copy:
        src: ../getHash/API
        dest: /usr/local/network/
        mode: 0755
        remote_src: false
    - name: "Copy index"
      copy:
        src: ../getHash/index.html
        dest: /usr/local/network/
        mode: 0755
        remote_src: false
    - name: "Create temp folder"
      file:
        path: /usr/local/network/temp
        state: directory
    - name: "Start backend with screen"
      command: "screen -d -m -S getHash /usr/local/network/API -api"
