- hosts: "localhost"
  become: true
  name: "Install Golang"
  tasks:
    - name: "Get Golang"
      ansible.builtin.copy:
        src: ../golang/go1.18.linux-amd64.tar.gz
        dest: /tmp/go1.18.linux-amd64.tar.gz
        mode: 0777
        remote_src: false
    - name: "Extract golang"
      shell: "tar -C /usr/local -xzf /tmp/go1.18.linux-amd64.tar.gz"
    - name: "Add go to path"
      shell: "echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc"
    - name: "Copy getHash folder on aaron"
      copy:
        src: ../getHash
        dest: /tmp/
        mode: 0755
        remote_src: false
    - name: "Build golang"
      command: "cd /tmp/getHash && go build"