- hosts: "aaron"
  become: true
  tasks:
    - name: addP1
      command: "sudo ip a add 10.8.0.2/24 dev enp9s0"
      ignore_errors: true
    - name: enableP1
      command: "sudo ip link set enp9s0 up"
      ignore_errors: true
    - name: addP2
      command: "sudo ip a add 10.8.1.2/24 dev enp10s0"
      ignore_errors: true
    - name: enableP2
      command: "sudo ip link set enp10s0 up"
      ignore_errors: true
- hosts: "peaurouge"
  become: true
  tasks:
    - name: addP1
      command: "sudo ip a add 10.8.0.1/24 dev enp9s0"
      ignore_errors: true
    - name: enableP1
      command: "sudo ip link set enp9s0 up"
      ignore_errors: true
    - name: LinkPeauRougeCyclope
      command: "sudo ip route add 10.8.1.1 via 10.8.0.2"
      ignore_errors: true
- hosts: "cyclope"
  become: true
  tasks:
    - name: addP2
      command: "sudo ip a add 10.8.1.1/24 dev enp10s0"
      ignore_errors: true
    - name: enableP1
      command: "sudo ip link set enp10s0 up"
      ignore_errors: true
    - name: LinkPeauRougeCyclope
      command: "sudo ip route add 10.8.0.1 via 10.8.1.2"
      ignore_errors: true
