- hosts: "aaron"
  become: true
  name: "Init pki infra"
  tasks:
    - name: "Create Pki directory"
      file:
        path: /root/pki
        state: directory
        mode: 0640
    - name: "Create pki configuration directory"
      file:
        path: /root/pki/config
        state: directory
        mode: 0640
    - name: "Create pki Certificates directory"
      file:
        path: /root/pki/certificats
        state: directory
        mode: 0640
    - name: "Create pki db"
      file:
        path: /root/pki/db/ca.db.certs
        state: directory
        mode: 0640
    - name: "Init pki Db"
      shell: "echo '01'> /root/pki/db/ca.db.serial"
    - name: "Init cert index"
      shell: "cp /dev/null /root/pki/db/ca.db.index"
    - name: "Copy ca.config in config from host"
      ansible.builtin.copy:
        src: ../Pki/ca.config
        dest: /root/pki/config/ca.config
        mode: 0640
        remote_src: false
- hosts: "aaron"
  become: true
  name: "Generate CA"
  tasks:
    - name: "Generate ca.key"
      shell: "cd /root/pki && sudo openssl genrsa -out certificats/ca.key"
    - name: "Generate ca.req in certificats"
      shell: "cd /root/pki && sudo openssl req -new -key certificats/ca.key -out certificats/ca.req -config config/ca.config"
    - name: "Generate ca.crt in certificats"
      shell: "cd /root/pki && sudo openssl x509 -req -days 3000 -in certificats/ca.req -signkey certificats/ca.key -out certificats/ca.crt"
    - name: "Generate ca.der in certificats"
      shell: "cd /root/pki && sudo openssl x509 -in certificats/ca.crt -out certificats/ca.der -outform DER"
