- hosts: "cyclope"
  name: "Setup Cyclope Redis"
  become: true
  tasks:
    - name: "Install Redis"
      apt:
        update_cache: yes
        name: "redis-server"
    - name: "Edit Line if exist"
      ignore_errors: true
      lineinfile:
        path: /etc/redis/redis.conf
        regexp: "supervised"
        line: supervised systemd
        state: present
        backup: yes
    - name: "Insert if line not exist"
      ignore_errors: true
      lineinfile:
        path: /etc/redis/redis.conf
        line: supervised systemd
        state: present
        backup: yes
    - name: "bind redis to localhost and cyclope"
      lineinfile:
        path: /etc/redis/redis.conf
        regexp: "bind 127.0.0.1 ::1"
        line: bind 127.0.0.1 ::1 10.8.3.1 10.8.1.1
    - name: "Edit Line if exist and add password"
      ignore_errors: true
      lineinfile:
        path: /etc/redis/redis.conf
        regexp: "requirepass"
        line: requirepass {{ redis_password }}
        state: present
        backup: yes
    - name: "Insert if line not exist and add password"
      ignore_errors: true
      lineinfile:
        path: /etc/redis/redis.conf
        line: requirepass {{ redis_password }}
        state: present
        backup: yes
    - name: "Restart redis"
      shell: sudo systemctl restart redis.service
